load("@rules_cc//cc:defs.bzl", "cc_test")

cc_test(
    name = "update_control_hsm_test",
    srcs = ["update_control_hsm_test.cpp"],
    deps = [
        "//eta_hsm/macros/example:update_control_hsm",
        "@googletest//:gtest_main",
    ],
)
