load("@rules_cc//cc:defs.bzl", "cc_test")

cc_test(
    name = "event_bucket_test",
    srcs = ["event_bucket_test.cpp"],
    deps = [
        "//eta_hsm/utils",
        "@googletest//:gtest_main",
    ],
)

cc_test(
    name = "timer_test",
    srcs = ["timer_test.cpp"],
    deps = [
        "//eta_hsm/utils",
        "@googletest//:gtest_main",
    ],
)

cc_test(
    name = "time_tracker_test",
    srcs = ["time_tracker_test.cpp"],
    deps = [
        "//eta_hsm/utils",
        "@googletest//:gtest_main",
    ],
)
