load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
    name = "macros",
    srcs = ["HsmMacrosImpl.hpp"],
    hdrs = ["HsmMacros.hpp"],
    visibility = ["//visibility:public"],
    deps = [
        "//eta_hsm",
    ],
)
