load("@rules_cc//cc:defs.bzl", "cc_test")

cc_test(
    name = "cd_player_test",
    srcs = ["cd_player_test.cpp"],
    deps = [
        "//eta_hsm/examples/cd_player",
        "@googletest//:gtest_main",
    ],
)
