load("@rules_cc//cc:defs.bzl", "cc_test")

cc_test(
    name = "canonical_test",
    srcs = ["canonical_test.cpp"],
    deps = [
        "//eta_hsm/examples/canonical",
        "@googletest//:gtest_main",
    ],
)
