load("@rules_cc//cc:defs.bzl", "cc_test")

cc_test(
    name = "example_control_test",
    srcs = ["example_control_test.cpp"],
    deps = [
        "//eta_hsm/examples/controller:example_control",
        "@googletest//:gtest_main",
    ],
)
